function [fitresult, gof] = createFit(x, cv)
%CREATEFIT(CV)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: cv
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Sep-2018 11:00:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, cv );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [225 16 2.28344711019903];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




