function [fitresult, gof] = createFit(x, cv2)
%CREATEFIT(CV2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: cv2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Sep-2018 11:01:54


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, cv2 );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [231 16 2.34278990132004];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




